index:
    path: /{vueRouting}
    controller: App\Controller\IndexController::index
    requirements: 
      vueRouting: "^(?!api|_(profiler|wdt)).*"

login:
    path: /api/login
    controller: App\Controller\SecurityController::apiLogin
    methods: POST

app_login:
    path: /api/login_check
    controller: App\Controller\SecurityController::login
    methods: GET

register:
    path: /api/register
    controller: App\Controller\SecurityController::register